      - name: Move jar to deployment folder and zip
        run: |
          mkdir -p deploy
          cp backend/target/*.jar deploy/application.jar
          echo "web: java -jar application.jar" > deploy/Procfile  # <<< ADD THIS LINE
          cd deploy
          zip ../app.zip application.jar Procfile                  # <<< ZIP BOTH FILES
          cd ..
