server.port=5000
  
spring.application.name=backend
logging.level.org.springframework.security=DEBUG
spring.datasource.url=jdbc:mysql://awseb-e-svmmyrpuwq-stack-awsebrdsdatabase-ujkff0sae5lw.c1owam0mgaqh.eu-north-1.rds.amazonaws.com:3306/ebdb
spring.datasource.username=dbuser
spring.datasource.password=CeLeNe#4!1
  
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
  
# Stripe Configuration
stripe.secret-key=sk_test_51CodWNGTTW14r8XkddL5pLlsNvEUbiUPz2HKukwSyaFS6fDbvY1xMwLiRkU6btkNj6I593e85iS35cWwMrWDL26Z00oWFqf5SG
stripe.public-key=pk_test_PgWSKAkynPEgvZGCxLWEiA81
  
# AWS Configuration
aws.access-key-id=AKIAWQRKXBRNBC7H2D6U
aws.secret-access-key=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
aws.s3BucketName=lab-away-images
aws.region=eu-north-1

