server.port=5000

spring.application.name=backend

spring.datasource.url=jdbc:mysql://awseb-e-svmmyrpuwq-stack-awsebrdsdatabase-ujkff0sae5lw.c1owam0mgaqh.eu-north-1.rds.amazonaws.com:3306/ebdb
spring.datasource.username=dbuser
spring.datasource.password=CeLeNe#4!1

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Stripe Configuration
stripe.secret-key=sk_test_51CodWNGTTW14r8XkddL5pLlsNvEUbiUPz2HKukwSyaFS6fDbvY1xMwLiRkU6btkNj6I593e85iS35cWwMrWDL26Z00oWFqf5SG
stripe.public-key=pk_test_PgWSKAkynPEgvZGCxLWEiA81

# PayPal Configuration
paypal.client-id=AS62grdrV6Q17jNHddKB-baigoUHzRFyNrSIU92XqU_8X33dbdiyDtPwW56OjQ7JkfaH-9RxKmY26oI9
paypal.client-secret=EKJQAXkB6PcGcSU2uEXHj4Omzzxudz95sZSq0iw1TEzFoQnLko8KBDkXSxoCIQZ38_cAWeCGyfcapY2B

# AWS Configuration
aws.access-key-id=AKIAWQRKXBRNBC7H2D6U
aws.secret-access-key=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
aws.s3BucketName=lab-away-images
aws.region=eu-north-1

# Maximum size for individual files
spring.servlet.multipart.max-file-size=10MB

# Maximum size for the entire request
spring.servlet.multipart.max-request-size=10MB

app.frontend-url=http://lab-away.com.s3-website.eu-north-1.amazonaws.com/

# SMTP configuration
spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.port=587
spring.mail.from=sales@lab-away.com
spring.mail.username=AKIAWQRKXBRNH6G6PLJY
spring.mail.password=BAlmWRDqTysyBmV4wIcGs5lL229lf6Nq/01loqbm9lqA
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: default from address
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

jwt.secret=wZbKJgK1uAfVjMxY5tLmS5tvFZ4nFg7NQ2Vv35BlWnA=