server.port=5000

spring.application.name=backend
logging.level.org.springframework.security=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

smtp.username=${SMTP_USERNAME}
smtp.password=${SMTP_PASSWORD}
smtp.fromEmail=${SMTP_FROM_EMAIL}

db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.engine=${DB_ENGINE}
db.host=${DB_HOST}
db.port=${DB_PORT}
db.name=${DB_NAME}
db.instanceIdentifier=${DB_INSTANCE_IDENTIFIER}

jwt.secret=${JWT_SECRET}

aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.s3.bucketName=${AWS_S3_BUCKET_NAME}
aws.region=${AWS_REGION}

# Prerendered HTML bucket
aws.s3.prerenderedBucketName=lab-away-prerendered

paypal.clientId=${PAYPAL_CLIENT_ID}
paypal.secret=${PAYPAL_SECRET}

stripe.publicKey=${STRIPE_PUBLIC_KEY}
stripe.secretKey=${STRIPE_SECRET_KEY}

