server.port=5000
  
spring.application.name=backend
logging.level.org.springframework.security=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

smtp.username=${SMTP_USERNAME}
smtp.password=${SMTP_PASSWORD}
smtp.fromEmail=${SMTP_FROM_EMAIL}

db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.engine=${DB_ENGINE}
db.host=${DB_HOST}
db.port=${DB_PORT}
db.name=${DB_NAME}
db.instanceIdentifier=${DB_INSTANCE_IDENTIFIER}

jwt.secret=${JWT_SECRET}

aws.s3.bucketName=${AWS_S3_BUCKET_NAME}
aws.region=${AWS_REGION}

# paypal.clientId=${PAYPAL_CLIENT_ID}
# paypal.secret=${PAYPAL_SECRET}

paypal.clientId=AS62grdrV6Q17jNHddKB-baigoUHzRFyNrSIU92XqU_8X33dbdiyDtPwW56OjQ7JkfaH-9RxKmY26oI9
paypal.secret=EKJQAXkB6PcGcSU2uEXHj4Omzzxudz95sZSq0iw1TEzFoQnLko8KBDkXSxoCIQZ38_cAWeCGyfcapY2B

stripe.publicKey=pk_test_51TY7HLFRf01HYtGQw6tarnaoAONYTc9IPgPEgJILJwPFtTcC57PkrqvTKO8IlHmUlnCqAVw8sD09UI40Pc8sZfRo00IumohumY
stripe.secretKey=sk_test_51TY7HLFRf01HYtGQNCvEFOI5GO1TWJNfHnjbYs4OIDrkH0jCW1Z6CFkT0PydLqbDpu0WPQcNKqw6I9JSeyNYTeS900e2I4IZ2j

# Google Analytics
ga4.measurement-id=${GA4_MEASUREMENT_ID}
ga4.api-secret=${GA4_API_SECRET}